//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RamshurRatApp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please fill all the configuration parameters.")]
        public string CONFIG_PARAM {
            get {
                return ((string)(this["CONFIG_PARAM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please select the channel to be used.")]
        public string chnl {
            get {
                return ((string)(this["chnl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please select the mode of operation to be used.")]
        public string mode {
            get {
                return ((string)(this["mode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T1, T3, T4, and T8 should be in the relation ((T1 * 3600) / T4) > (T3 * T8).")]
        public string T1T4T3_dependancy {
            get {
                return ((string)(this["T1T4T3_dependancy"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Addition of the parameters T5,T6,T7 should be less than the value of the paramate" +
            "r T8.")]
        public string T8T5T6T7dependency {
            get {
                return ((string)(this["T8T5T6T7dependency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The values T8, T9 and T10 should be in the realtionT3 > T10 >T9 .")]
        public string T3T9T10dependency {
            get {
                return ((string)(this["T3T9T10dependency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please enter the sampling rate.")]
        public string samplingrate {
            get {
                return ((string)(this["samplingrate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please enter the ADC resolution.")]
        public string adcresolution {
            get {
                return ((string)(this["adcresolution"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Configurations successfully uploaded on the device.")]
        public string success {
            get {
                return ((string)(this["success"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The value of T1 is out of the specified range. Please take the cursor to the part" +
            "icular field to see the specified range.")]
        public string param_range {
            get {
                return ((string)(this["param_range"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The value of T2 is out of the specified range. Please take the cursor to the part" +
            "icular field to see the specified range.")]
        public string param_rangeT2 {
            get {
                return ((string)(this["param_rangeT2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The value of T3 is out of the specified range. Please take the cursor to the part" +
            "icular field to see the specified range.")]
        public string param_rangeT3 {
            get {
                return ((string)(this["param_rangeT3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The value of T4 is out of the specified range. Please take the cursor to the part" +
            "icular field to see the specified range.")]
        public string param_rangeT4 {
            get {
                return ((string)(this["param_rangeT4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The value of T5 is out of the specified range. Please take the cursor to the part" +
            "icular field to see the specified range.")]
        public string param_rangeT5 {
            get {
                return ((string)(this["param_rangeT5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The value of T6 is out of the specified range. Please take the cursor to the part" +
            "icular field to see the specified range.")]
        public string param_rangeT6 {
            get {
                return ((string)(this["param_rangeT6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The value of T7 is out of the specified range. Please take the cursor to the part" +
            "icular field to see the specified range.")]
        public string param_rangeT7 {
            get {
                return ((string)(this["param_rangeT7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The value of T8 is out of the specified range. Please take the cursor to the part" +
            "icular field to see the specified range.")]
        public string param_rangeT8 {
            get {
                return ((string)(this["param_rangeT8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The value of T9 is out of the specified range. Please take the cursor to the part" +
            "icular field to see the specified range.")]
        public string param_rangeT9 {
            get {
                return ((string)(this["param_rangeT9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The value of T10 is out of the specified range. Please take the cursor to the par" +
            "ticular field to see the specified range.")]
        public string param_rangeT10 {
            get {
                return ((string)(this["param_rangeT10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Device connected")]
        public string HHU_CONNECTED {
            get {
                return ((string)(this["HHU_CONNECTED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Device not connected")]
        public string HHU_DisCONNECTED {
            get {
                return ((string)(this["HHU_DisCONNECTED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to configure parameters on the device.")]
        public string Config_FAIL {
            get {
                return ((string)(this["Config_FAIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Configuration parameters successfully fetched.")]
        public string DISCOVER_PARA_SUCCESS {
            get {
                return ((string)(this["DISCOVER_PARA_SUCCESS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Failed to fetch the configuration parameters.")]
        public string DISCOVER_PARA_FAIL {
            get {
                return ((string)(this["DISCOVER_PARA_FAIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Device  connected")]
        public string CONNECTION {
            get {
                return ((string)(this["CONNECTION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GUIADANCE {
            get {
                return ((string)(this["GUIADANCE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string URL {
            get {
                return ((string)(this["URL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Do you want to reset the timing configuration values?")]
        public string RESET_CONFIRM {
            get {
                return ((string)(this["RESET_CONFIRM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is the first file in the collection.")]
        public string First_File {
            get {
                return ((string)(this["First_File"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please check the application - device connectivity and try again  getting  the co" +
            "nfigurations.")]
        public string CONNECTION1 {
            get {
                return ((string)(this["CONNECTION1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cannot find the device for establishing the connection.")]
        public string CONNECTION2 {
            get {
                return ((string)(this["CONNECTION2"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please enter valid display range for X-axis.")]
        public string xrange_empty {
            get {
                return ((string)(this["xrange_empty"]));
            }
            set {
                this["xrange_empty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Minimum display range is 100, please enter display range greater than 100 and les" +
            "s than 1000.")]
        public string xrange_less_error {
            get {
                return ((string)(this["xrange_less_error"]));
            }
            set {
                this["xrange_less_error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Display range should be decimal.")]
        public string xrange_number_only {
            get {
                return ((string)(this["xrange_number_only"]));
            }
            set {
                this["xrange_number_only"] = value;
            }
        }
    }
}
